config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :universities

  resources :rooms

  root 'rooms#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
	def self.search(query)
	  univ = nil
	  if query[0] == ''
	  	return Room
	  end
	  
	  if query[1] == ''
	  	univ_id = 404
	  else
		  univ = University.where("univ_name like ?", "%#{query[1]}%").last
		  univ_id = univ.univ_id rescue univ_id = 404
	  end
	  
	  if query[0] =~ /^\d+$/
	  	return Room.where("acpt_distance < ? and univ_id like ?", "#{query[0]}","%#{univ_id}%")
	  	#return Room.where("acpt_distance < ?", "#{query[0]}")
	  elsif query[0] =~ /^\$\d+$/
	  	money = /^\$(\d+)$/.match(query[0])[1]
	  	return Room.where("rent < ? and univ_id like ?", money, "%#{univ_id}%")
	  else
	  	return Room.where("(address like ? or desc like ?) and univ_id like ?", "%#{query[0]}%", "%#{query[0]}%","%#{univ_id}%")
	  end
	end
	
validates :address, presence: true
validates :rent, presence: true
#validates :util_fee, presence: true
validates :apt_roomnum, presence: true
has_attached_file :image
validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/rooms_controller.rb
require 'geocoder'
require "rubygems"
require "nokogiri"
require "open-uri"

class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
	# import the @universities entries
	#@universities = University.all
	#set the search functionality
	
	if params[:search]
		@rooms = Room.search(params[:search]).order("rent")
	else
		@rooms = Room.all
	end
	
    @hash = Gmaps4rails.build_markers(@room) do |room, marker|
  		marker.lat room.latitude
  		marker.lng room.longitude
	end
	
	#No need to call this function again. Used for deleting waste entries
	#delete_waste_entries
	
	#Using for pull info from Craigslist.org, Craigslist.org all rights reserved
	#pull_data_from_craiglist
	
	#controller should change the instance variable 
	#@rooms = Room.all	 #done in calculate_distance
	#If using this, "can't modify frozen Hash" may happen
	#calculate_distance
  end
  
  def refresh_the_home
  	delete_waste_entries
  	pull_data_from_craiglist
  	calculate_distance
  	@room = Room.all
  end
  helper_method :refresh_the_home;
  
  # GET /rooms/1
  # GET /rooms/1.json
  def show
      @universities = University.all
      @hash = Gmaps4rails.build_markers(@room) do |room, marker|
          marker.lat room.latitude
          marker.lng room.longitude
      end

  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
	
    respond_to do |format|
      if @room.save
	  	@universities = University.all
		@universities.each do |university|
			if university.univ_id == @room.univ_id
				#puts @room.distance_to(university.univ_addr)
				@room.update_attribute :acpt_distance, @room.distance_to(university.univ_addr)
				break
			end
		end
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        @universities = University.all
		@universities.each do |university|
			if university.univ_id == @room.univ_id
				puts @room.distance_to(university.univ_addr)
				@room.update_attribute :acpt_distance, @room.distance_to(university.univ_addr)
				break
			end
		end
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def pull_data_from_craiglist
  	@entryURL = []
  	home_url = "http://sfbay.craigslist.org/apa/"
  	list = Nokogiri::HTML(open(home_url))
  	list.css('#pagecontainer #toc_rows .content .row .i').each do |row|
  		second_half_url = row['href']
  		entry_url = 'http://sfbay.craigslist.org' + second_half_url
  		@entryURL.push(entry_url)
  		if @entryURL.size == 20
  			break
  		end
  	end
  	@entryURL.each do |url|
  		@room = Room.new
	  	entry = Nokogiri::HTML(open(url))
  		entry.css('#pagecontainer .body .userbody .mapAndAttrs div:nth-child(2)').each do |elem|
  			@room.address = elem.content
  		end
  		
  		entry.css('#pagecontainer .body .userbody .mapAndAttrs .attrgroup span:first-child b:first-child').each do |elem|
  			@room.apt_roomnum = elem.content
  		end
  		
  		entry.css('#pagecontainer .body .userbody .mapAndAttrs .attrgroup span:first-child b:nth-child(2)').each do |elem|
  			@room.apt_bathnum = elem.content
  		end
  		
  		entry.css('#pagecontainer .body .userbody .iw #ci #iwi').each do |elem|
  				@room.image_url = elem['src'] if String(elem['src']) rescue break
  		end
  		
  		entry.css('#pagecontainer .body .postingtitle').each do |elem|
  			@room.desc = elem.content
  			#rent = elem.content.scan(/\$(\d+)/)[1]
  			if /\$(\d+)/.match(elem.content)
  				rent = /\$(\d+)/.match(elem.content)[1]
  			else rent = "not matched"
  			end
  			
			if is_number(rent)
  				@room.rent = rent.to_f
  			else
  				@room.rent = -1.0
  			end
  		end
  		
  		#calculate distance for this address
  		@room.univ_id = 1
=begin
  		@universities = University.all
  		@universities.each do |university|
  			if university.univ_id == @room.univ_id
  				@room.acpt_distance = @room.distance_to(university.univ_addr)
  				puts @room.acpt_distance
  				break
  			end
  		end
=end  		
  		#check whether this room was already listed
  		found = false
  		@rooms.each do |record|
  			if record.address == @room.address
  				found = true
  				#if @room.update(room_params)
  				#else
  				#	puts @room.errors.full_messages
  				#end
  				break
  			end
  		end
  		if found == false
  			if @room.save
  			else
        		puts @room.errors.full_messages
  			end
  		end
  		
  		#address = entry.css('#pagecontainer .body .userbody .mapAndAttrs .attrgroup ').content
  	end
  end		
  helper_method :pull_data_from_craiglist;
  
  def is_number(rent)
    true if Float(rent) rescue false
  end
  
  def calculate_distance
  	@universities = University.all
  	@rooms = Room.all
  	@rooms.each do |room|
  		counted = false
    	@universities.each do |university|
    		if university.univ_id == room.univ_id
				room.update_attribute :acpt_distance, room.distance_to(university.univ_addr)
				counted = true
			end
		end
		if counted
			puts "distance calculated successfully"
		else room.update_attribute :acpt_distance, -1.0
		end
	end
  end 
  helper_method :calculate_distance;
  
  def delete_waste_entries
  	@rooms = Room.all
  	@rooms.each do |room|
  		# this is indicator of waste room entry. developer can change it
  		if room.entry_id != 1 || room.entry_id != 2
  			room.delete
  		end 
=begin
  		if room.acpt_distance.to_s =='' || room.acpt_distance == -1.0
  			room.delete
  		end
		"do nothing" if Float(room.acpt_distance)  rescue room.delete 
=end
  	end
  end
  helper_method :delete_waste_entries;
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params

      params.require(:room).permit(:entry_id, :latitude, :longitude, :address, :rent, 
      :util_fee, :apt_roomnum, :apt_bathnum, 
      :apt_gender, :univ_id, :acpt_distance, 
      :desc, :usr_name, :landlord, :image_url, :email, :tel, :image)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room, :html => {:multipart =>true}) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <!-- <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div> -->
 <!-- <div class="field">
    <%#= f.label :longitude %><br>
    <%#= f.text_field :longitude %>
  </div> -->
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :rent %><br>
    <%= f.text_field :rent %>
  </div>
  <div class="field">
    <%= f.label :utility_fee %><br>
    <%= f.text_field :util_fee %>
  </div>
  <div class="field">
    <%= f.label :Quantity_of_room %><br>
    <%= f.number_field :apt_roomnum %>
  </div>
  <div class="field">
    <%= f.label :Quantity_of_bathroom %><br>
    <%= f.number_field :apt_bathnum %>
  </div>
  <div class="field">
    <%= f.label :Roommate_gender %><br>
    <%= f.text_field :apt_gender %>
  </div>
  <div class="field">
    <%= f.label :university_code %><br>
    <%= f.number_field :univ_id, :value => '1' %>
  </div>

  <div class="field">
    <%= f.label :Email%><br>
    <%= f.text_area :email, :value => current_user.email %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  
    <div class="field">
    <%= f.label :image %><br/>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<!--Using helper method is holly terrible!!-->
<!--%delete_waste_entries%-->
<!--%pull_data_from_craiglist%-->
<!--%calculate_distance%-->

<h1>Rooms Available</h1>
<div class="table-responsive">
	
<table class="table table-striped">	
  <thead>
    <tr>
      <!--th>Entry</th>
      <th>Latitude</th>
      <th>Longitude</th-->
      <th><center>Address</center></th>
      <th><center>Rent</center></th>
      <!--th>Util fee</th-->
      <th><center>Room Number</center></th>
      <!--th>Apt bathnum</th-->
      <!--th><center>Gender</center></th-->
      <!--th>Univ</th-->
      <th><center>Distance</center></th>
      <th><center>Description</center></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.order('rent').each do |room| %>
      <tr>
        <!--Commented by Chen Sun:no need to show these attributes-->
        <!--td><%= room.entry_id %></td-->
        <!--td><%= room.latitude %></td-->
        <!--td><%= room.longitude %></td-->
        <td><%= room.address %></td>
        <td>
        	<% if room.rent == -1.0 %>
        		<%="N/A"%>
        	<% else %>
        		<%=room.rent%>
        	<%end%>
        </td>
        <!--td><%= room.util_fee %></td-->
        <td>
        	<center>
        		<%if room.apt_roomnum <= 0%>
        			N/A
        		<%else%>
        			<%= room.apt_roomnum %>
        		<%end%>
        	</center>
        </td>
        <!--td><%= room.apt_bathnum %></td-->
        <!--td><%= room.apt_gender %></td-->
        <!--td><%= room.univ_id %></td-->
        <!--%room.acpt_distance=room.distance_to('500 El Camino Real, Santa Clara') %-->
        <td>
        	<% if room.acpt_distance.to_s =='' || room.acpt_distance == -1.0%>
				N/A
        	<% elsif room.acpt_distance < 1.0 %>
        		<%='< 1 mile'%>
			<% else %>
			  	<%=room.acpt_distance.to_i.to_s + ' miles'%>
			<%end%>
        </td>
        <td><%= room.desc %></td>
        <td><%= link_to 'Show', room, class:"btn btn-sm btn-default" %></td>
        
		<%if room.email == current_user.email%>
		<td><%= link_to 'Edit', edit_room_path(room), class:"btn btn-sm btn-success" %></td>
        <td><%= link_to 'Destroy', room, method: :delete,class:"btn btn-sm btn-warning", data: { confirm: 'Are you sure?' } %></td>
		<%else%>
		<td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </td>
		<td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
		<%end%>
      </tr>
    <% end %>
  </tbody>

</table>
</div>
<br>

<%= link_to 'New Room', new_room_path,class: "btn btn-large btn-primary" %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<!--<p id="notice"><%= notice %></p>-->

<h1 style="color:#cdbfe3">Apartment Information</h1>
<table class="table table-striped" width="500" >
<tbody>
<tr>
  <td><strong>Latitude:</strong></td>
  <td><%= @room.latitude %></td>
</tr>
</tbody>
<tr>
  <td><strong>Longitude:</strong></td>
  <td><%= @room.longitude %></td>
</tr>

<tr>
  <td><strong>Address:</strong></td>
  <td><%= @room.address %></td>
</tr>

<tr>
  <td><strong>Rent:</strong></td>
  <td><%= @room.rent %></td>
</tr>

<tr>
  <td><strong>Utility Fees:</strong></td>
  <td><%= @room.util_fee %></td>
</tr>

<tr>
  <td><strong>Quantity of Room:</strong></td>
  <td><%= @room.apt_roomnum %></td>
</tr>

<tr>
  <td><strong>Quantity of Bathroom:</strong></td>
  <td><%= @room.apt_bathnum %></td>
</tr>

<tr>
  <td><strong>Roommate gender:</strong></td>
  <td><%= @room.apt_gender %></td>
</tr>

<tr>
  <td><strong>University</strong></td>
  <td>
  <% @universities.each do |university|%>
     <% if university.univ_id == @room.univ_id %>
  		<%= university.univ_name %>
  <%end%>
  <%end%>
</td>
</tr>

<tr>
  <td><strong>Distance from U:</strong></td>
  <td><%= @room.acpt_distance %></td>
</tr>

<tr>
  <td><strong>Commons:</strong></td>
  <td><%= @room.desc %></td>
</tr>
</tbody>
</table>

<p><strong>Picture:</strong></p>
<%if @room.image?%>

<div class="aptpic">
<%= image_tag @room.image.url %>
</div>

<%else%>
<p>There is no picture for this apartment.</p>
<%end%>



<p><strong>Mark on Map:</strong></p>

<div style='width: 600px;'>
<div id="map" style='width: 600px; height: 300px;'></div>
</div>
<p></p>
<%= link_to 'Back', rooms_path,class:"btn btn-sm btn-info" %>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(15);
});
</script>