config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :universities

  resources :rooms

  root 'rooms#index'

end

app/models/university.rb
class University < ActiveRecord::Base
validates :univ_addr, presence: true
validates :univ_id, presence: true
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_params
      params.require(:university).permit(:univ_name, :univ_id, :univ_addr)
    end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/universities/_form.html.erb
<%= form_for(@university) do |f| %>
  <% if @university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% @university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :univ_name %><br>
    <%= f.text_field :univ_name %>
  </div>
  <div class="field">
    <%= f.label :univ_id %><br>
    <%= f.number_field :univ_id %>
  </div>
  <div class="field">
    <%= f.label :univ_addr %><br>
    <%= f.text_field :univ_addr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing university</h1>

<%= render 'form' %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<h1>Listing universities</h1>

<table>
  <thead>
    <tr>
      <th>Univ name</th>
      <th>Univ</th>
      <th>Univ addr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universities.each do |university| %>
      <tr>
        <td><%= university.univ_name %></td>
        <td><%= university.univ_id %></td>
        <td><%= university.univ_addr %></td>
        <td><%= link_to 'Show', university %></td>
        <td><%= link_to 'Edit', edit_university_path(university) %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>New university</h1>

<%= render 'form' %>

<%= link_to 'Back', universities_path %>

app/views/universities/show.html.erb
<!--><p id="notice"><%= notice %></p>-->

<p>
  <strong>Univ name:</strong>
  <%= @university.univ_name %>
</p>

<p>
  <strong>Univ:</strong>
  <%= @university.univ_id %>
</p>

<p>
  <strong>Univ addr:</strong>
  <%= @university.univ_addr %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>